package nn

import (
	"encoding/binary"
	"errors"
	"io"
	"os"
)

///
/// <summary>
///   RawSample is one position stored on disk exactly as generated by
///   self-play: a board, the side to move, and the game result from White's
///   perspective (+1 white win, 0 draw, -1 white loss).
/// </summary>
/// <param name="Board">64 squares, sign encodes color.</param>
/// <param name="Stm">Side to move: +1 white, -1 black.</param>
/// <param name="Target">Game result from White's perspective.</param>
type RawSample struct {
	Board  [64]int8
	Stm    int8
	Target float32
}

///
/// <summary>
///   datasetMagic identifies a raw self-play dataset file.
/// </summary>
var datasetMagic = [8]byte{'C', 'H', 'E', 'S', 'S', 'D', 'A', 'T'}

///
/// <summary>
///   netMagic identifies a serialised network weight file.
/// </summary>
var netMagic = [8]byte{'C', 'H', 'E', 'S', 'S', 'N', 'N', '1'}

///
/// <summary>
///   DatasetWriter streams raw samples to a binary dataset file, writing the
///   magic header and count up front and finalising them on Close.
/// </summary>
/// <param name="f">Wrapped file.</param>
/// <param name="n">Sample count seen so far.</param>
type DatasetWriter struct {
	f *os.File
	n uint64
}

///
/// <summary>
///   NewDatasetWriter opens a streaming dataset writer over an existing file,
///   emitting the magic header and a placeholder count.
/// </summary>
/// <param name="f">Destination file.</param>
/// <returns>A writer accepting raw sample batches.</returns>
func NewDatasetWriter(f *os.File) *DatasetWriter {
	f.Write(datasetMagic[:])
	binary.Write(f, binary.LittleEndian, uint64(0))
	return &DatasetWriter{f: f, n: 0}
}

///
/// <summary>
///   Write appends a batch of raw samples to the dataset stream.
/// </summary>
/// <param name="batch">Samples to append.</param>
/// <returns>An error when the underlying write fails.</returns>
func (d *DatasetWriter) Write(batch []RawSample) error {
	for _, s := range batch {
		if err := binary.Write(d.f, binary.LittleEndian, s.Board); err != nil {
			return err
		}
		if err := binary.Write(d.f, binary.LittleEndian, s.Stm); err != nil {
			return err
		}
		if err := binary.Write(d.f, binary.LittleEndian, s.Target); err != nil {
			return err
		}
		d.n++
	}
	return nil
}

///
/// <summary>
///   Close patches the sample count into the header alongside the magic.
/// </summary>
/// <returns>An error when the count cannot be written.</returns>
func (d *DatasetWriter) Close() error {
	if _, err := d.f.Seek(int64(len(datasetMagic)), io.SeekStart); err != nil {
		return err
	}
	return binary.Write(d.f, binary.LittleEndian, d.n)
}

///
/// <summary>
///   LoadRawDataset reads the raw binary dataset without feature encoding,
///   preserving boards and the stored White-perspective targets.
/// </summary>
/// <param name="path">Binary dataset path.</param>
/// <returns>The raw samples, or an error.</returns>
func LoadRawDataset(path string) ([]RawSample, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	hdr := make([]byte, 8)
	if _, err := io.ReadFull(f, hdr); err != nil {
		return nil, err
	}
	if string(hdr) != string(datasetMagic[:]) {
		return nil, errors.New("dataset: bad magic")
	}
	var count uint64
	if err := binary.Read(f, binary.LittleEndian, &count); err != nil {
		return nil, err
	}
	out := make([]RawSample, 0, count)
	for i := uint64(0); i < count; i++ {
		var raw RawSample
		if err := binary.Read(f, binary.LittleEndian, &raw.Board); err != nil {
			return nil, err
		}
		if err := binary.Read(f, binary.LittleEndian, &raw.Stm); err != nil {
			return nil, err
		}
		if err := binary.Read(f, binary.LittleEndian, &raw.Target); err != nil {
			return nil, err
		}
		out = append(out, raw)
	}
	return out, nil
}

///
/// <summary>
///   SaveDataset writes raw samples to a binary file.
/// </summary>
/// <param name="path">Destination path.</param>
/// <param name="samples">Samples to write.</param>
/// <returns>An error when the file cannot be created or written.</returns>
func SaveDataset(path string, samples []RawSample) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	if _, err := f.Write(datasetMagic[:]); err != nil {
		return err
	}
	if err := binary.Write(f, binary.LittleEndian, uint64(len(samples))); err != nil {
		return err
	}
	for _, s := range samples {
		if err := binary.Write(f, binary.LittleEndian, s.Board); err != nil {
			return err
		}
		if err := binary.Write(f, binary.LittleEndian, s.Stm); err != nil {
			return err
		}
		if err := binary.Write(f, binary.LittleEndian, s.Target); err != nil {
			return err
		}
	}
	return nil
}

///
/// <summary>
///   LoadDataset reads raw samples from a binary file and converts them into
///   training samples: sparse features encoded from the side to move's
///   perspective with the target re-baselined to the side to move.
/// </summary>
/// <param name="path">Binary dataset path.</param>
/// <returns>The converted samples, or an error.</returns>
func LoadDataset(path string) ([]Sample, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	hdr := make([]byte, 8)
	if _, err := io.ReadFull(f, hdr); err != nil {
		return nil, err
	}
	if string(hdr) != string(datasetMagic[:]) {
		return nil, errors.New("dataset: bad magic")
	}
	var count uint64
	if err := binary.Read(f, binary.LittleEndian, &count); err != nil {
		return nil, err
	}
	samples := make([]Sample, 0, count)
	for i := uint64(0); i < count; i++ {
		var raw RawSample
		if err := binary.Read(f, binary.LittleEndian, &raw.Board); err != nil {
			return nil, err
		}
		if err := binary.Read(f, binary.LittleEndian, &raw.Stm); err != nil {
			return nil, err
		}
		if err := binary.Read(f, binary.LittleEndian, &raw.Target); err != nil {
			return nil, err
		}
		target := raw.Target
		if raw.Stm < 0 {
			target = -target
		}
		samples = append(samples, Sample{Feats: EncodeFeatures(raw.Board, raw.Stm), Target: target})
	}
	return samples, nil
}

///
/// <summary>
///   Save writes the network weights to a binary file with a magic header.
/// </summary>
/// <param name="path">Destination path.</param>
/// <returns>An error when the file cannot be created or written.</returns>
func (n *Net) Save(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	if _, err := f.Write(netMagic[:]); err != nil {
		return err
	}
	for _, v := range []int32{int32(n.H1), int32(n.H2)} {
		if err := binary.Write(f, binary.LittleEndian, v); err != nil {
			return err
		}
	}
	for _, g := range n.Params() {
		for i := range g {
			if err := binary.Write(f, binary.LittleEndian, g[i]); err != nil {
				return err
			}
		}
	}
	if err := binary.Write(f, binary.LittleEndian, n.B3); err != nil {
		return err
	}
	return nil
}

///
/// <summary>
///   Load reads a network previously written by Save.
/// </summary>
/// <param name="path">Binary weights path.</param>
/// <returns>The reconstructed network, or an error.</returns>
func Load(path string) (*Net, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	hdr := make([]byte, 8)
	if _, err := io.ReadFull(f, hdr); err != nil {
		return nil, err
	}
	if string(hdr) != string(netMagic[:]) {
		return nil, errors.New("nn: bad magic")
	}
	var h1, h2 int32
	if err := binary.Read(f, binary.LittleEndian, &h1); err != nil {
		return nil, err
	}
	if err := binary.Read(f, binary.LittleEndian, &h2); err != nil {
		return nil, err
	}
	n := &Net{H1: int(h1), H2: int(h2)}
	n.W1 = make([]float32, FeatureCount*int(h1))
	n.B1 = make([]float32, int(h1))
	n.W2 = make([]float32, int(h1*h2))
	n.B2 = make([]float32, int(h2))
	n.W3 = make([]float32, int(h2))
	for _, g := range n.Params() {
		for i := range g {
			if err := binary.Read(f, binary.LittleEndian, &g[i]); err != nil {
				return nil, err
			}
		}
	}
	if err := binary.Read(f, binary.LittleEndian, &n.B3); err != nil {
		return nil, err
	}
	return n, nil
}